version: "3.7"

services:
  flask-api:
    build:
      context: ./backend
      dockerfile: ${BACK_DOCKERFILE}
      args:
        - FLASK_ENV=${FLASK_ENV}
        - FLASK_PORT=${FLASK_PORT}
    restart: unless-stopped
    container_name: flask-api
    image: hrlab/flask-api:0.0.0
    ports:
      - 0.0.0.0:${FLASK_PORT}:${FLASK_PORT}
    expose:
      - ${FLASK_PORT}
    volumes:
    - ./backend/src:/app/src
    networks:
      - app-net

  frontend:
    image: nginx:alpine
    restart: unless-stopped
    container_name: swagger-frontend
    ports:
      - ${NGINX_HOST}:${NGINX_PORT}:80
    expose:
      - ${NGINX_PORT}
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    networks:
      - app-net

networks:
  app-net:

