PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS tweets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mediaUrl VARCHAR(300),
  tweetDate VARCHAR(300),
  twitterId VARCHAR(100),
  handle VARCHAR(100),
  text VARCHAR(500) NOT NULL,
  profileUser VARCHAR(100),
  name VARCHAR(50),
  tweetLink VARCHAR(300),
  timestamp VARCHAR(300),
  query VARCHAR(200),
  type VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS tweets_sentiments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tweet_id INTEGER UNIQUE NOT NULL,
  sentiment VARCHAR(10),
  FOREIGN KEY (tweet_id) REFERENCES tweets(id)
);


CREATE TABLE IF NOT EXISTS tweets_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tweet_id INTEGER UNIQUE NOT NULL,
  tags VARCHAR(300),
  FOREIGN KEY (tweet_id) REFERENCES tweets(id)
);
